version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19000:19000"  # Expo default port
      - "19001:19001"  # Metro bundler
      - "19002:19002"  # Expo dev tools
      - "8081:8081"    # Metro bundler alternative port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      - EXPO_DEBUG=true
      - API_URL=http://backend:4000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/featured_jobs
      - NODE_ENV=development
      - PORT=4000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=featured_jobs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d featured_jobs"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
